#!/usr/bin/env node
/**
 * Git Hooks Manager for AI Commit Message Generation
 * 
 * This module manages the installation and configuration of Git hooks
 * for automatic commit message generation using MiniMax API.
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * GitHooksManager class for managing Git hooks
 */
class GitHooksManager {
  /**
   * Create a new GitHooksManager instance
   * @param {Object} options - Configuration options
   */
  constructor(options = {}) {
    this.gitDir = options.gitDir || '.git';
    this.hooksDir = options.hooksDir || path.join(this.gitDir, 'hooks');
  }
  
  /**
   * Check if Git repository exists
   * @returns {boolean} True if Git repository exists
   */
  isGitRepository() {
    return fs.existsSync(this.gitDir);
  }
  
  /**
   * Get current branch name
   * @returns {string} Current branch name
   */
  getCurrentBranch() {
    try {
      return execSync('git rev-parse --abbrev-ref HEAD', { encoding: 'utf-8' }).trim();
    } catch (error) {
      return 'unknown';
    }
  }
  
  /**
   * Get staged changes as diff
   * @returns {string} Git diff of staged changes
   */
  getStagedDiff() {
    try {
      return execSync('git diff --cached', { encoding: 'utf-8', maxBuffer: 10 * 1024 * 1024 });
    } catch (error) {
      return '';
    }
  }
  
  /**
   * Get list of staged files
   * @returns {string[]} Array of staged file paths
   */
  getStagedFiles() {
    try {
      const output = execSync('git diff --cached --name-only', { encoding: 'utf-8' });
      return output.trim().split('\n').filter(f => f);
    } catch (error) {
      return [];
    }
  }
  
  /**
   * Get repository root directory
   * @returns {string} Repository root path
   */
  getRepoRoot() {
    try {
      return execSync('git rev-parse --show-toplevel', { encoding: 'utf-8' }).trim();
    } catch (error) {
      return process.cwd();
    }
  }
  
  /**
   * Install Git hooks
   * @returns {boolean} True if installation successful
   */
  install() {
    if (!this.isGitRepository()) {
      console.error('❌ Error: Not a Git repository');
      return false;
    }
    
    // Ensure hooks directory exists
    if (!fs.existsSync(this.hooksDir)) {
      fs.mkdirSync(this.hooksDir, { recursive: true });
    }
    
    // Install prepare-commit-msg hook
    this._installPrepareCommitMsgHook();
    
    // Install pre-commit hook
    this._installPreCommitHook();
    
    // Configure Git settings
    this._configureGitSettings();
    
    console.log('✅ Git hooks installed successfully');
    console.log('📝 Configure with: git config hooks.commitProvider minimax');
    return true;
  }
  
  /**
   * Uninstall Git hooks
   * @returns {boolean} True if uninstallation successful
   */
  uninstall() {
    if (!this.isGitRepository()) {
      console.error('❌ Error: Not a Git repository');
      return false;
    }
    
    // Remove hook files
    const hooks = ['prepare-commit-msg', 'pre-commit'];
    for (const hook of hooks) {
      const hookPath = path.join(this.hooksDir, hook);
      if (fs.existsSync(hookPath)) {
        fs.unlinkSync(hookPath);
        console.log(`🗑️  Removed ${hook} hook`);
      }
    }
    
    console.log('✅ Git hooks uninstalled');
    return true;
  }
  
  /**
   * Install prepare-commit-msg hook
   * @private
   */
  _installPrepareCommitMsgHook() {
    const hookContent = `#!/bin/bash
# AI Commit Message Generation Hook
# Generated by lumoscribe2026 git-manager

# Get commit message file
COMMIT_MSG_FILE="$1"

# Check if AI generation is enabled
PROVIDER=$(git config hooks.commitProvider 2>/dev/null || echo "")
if [ "$PROVIDER" != "minimax" ]; then
    exit 0
fi

# Get staged changes
STAGED_DIFF=$(git diff --cached 2>/dev/null)
if [ -z "$STAGED_DIFF" ]; then
    exit 0
fi

# Check if message already exists (amend or no-message commit)
if [ -s "$COMMIT_MSG_FILE" ]; then
    exit 0
fi

# Generate commit message using Node.js script
cd "$(git rev-parse --show-toplevel)"
SCRIPT_DIR="$(dirname "$0")/../../lib"

if [ -f "$SCRIPT_DIR/hooks/prepare-commit-msg.js" ]; then
    node "$SCRIPT_DIR/hooks/prepare-commit-msg.js" "$COMMIT_MSG_FILE" 2>/dev/null
fi
`;
    
    const hookPath = path.join(this.hooksDir, 'prepare-commit-msg');
    fs.writeFileSync(hookPath, hookContent);
    fs.chmodSync(hookPath, '755');
    console.log('📄 Installed prepare-commit-msg hook');
  }
  
  /**
   * Install pre-commit hook
   * @private
   */
  _installPreCommitHook() {
    const hookContent = `#!/bin/bash
# Pre-commit Hook for Commit Message Preview
# Generated by lumoscribe2026 git-manager

# Check if AI preview is enabled
PREVIEW=$(git config hooks.preCommitPreview 2>/dev/null || echo "false")
if [ "$PREVIEW" != "true" ]; then
    exit 0
fi

# Get staged changes
STAGED_DIFF=$(git diff --cached 2>/dev/null)
if [ -z "$STAGED_DIFF" ]; then
    exit 0
fi

echo "🤖 AI is analyzing your changes..."

# This is a preview-only hook, it doesn't modify anything
exit 0
`;
    
    const hookPath = path.join(this.hooksDir, 'pre-commit');
    fs.writeFileSync(hookPath, hookContent);
    fs.chmodSync(hookPath, '755');
    console.log('📄 Installed pre-commit hook');
  }
  
  /**
   * Configure Git settings for AI integration
   * @private
   */
  _configureGitSettings() {
    try {
      // Set commit provider
      execSync('git config hooks.commitProvider minimax', { stdio: 'pipe' });
      
      // Set API base
      execSync('git config hooks.apiBase https://api.minimax.io/v1', { stdio: 'pipe' });
      
      console.log('⚙️  Git settings configured');
    } catch (error) {
      // Ignore errors if git config fails
    }
  }
}

// CLI interface
const args = process.argv.slice(2);
const command = args[0] || 'install';

const manager = new GitHooksManager();

switch (command) {
  case 'install':
    manager.install();
    break;
  case 'uninstall':
    manager.uninstall();
    break;
  case 'status':
    console.log('📊 Git Hooks Status');
    console.log('Repository:', manager.isGitRepository() ? 'Yes' : 'No');
    console.log('Current Branch:', manager.getCurrentBranch());
    console.log('Staged Files:', manager.getStagedFiles().length);
    break;
  default:
    console.log('Usage:');
    console.log('  node git-hooks.js install    - Install Git hooks');
    console.log('  node git-hooks.js uninstall  - Remove Git hooks');
    console.log('  node git-hooks.js status     - Show hook status');
}

export { GitHooksManager };
export default GitHooksManager;